# Generated by Django 3.1.4 on 2021-03-03 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='apellidoMaterno',
            new_name='apellidos',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='apellidoPaterno',
        ),
    ]
