# Generated by Django 3.1.4 on 2021-03-03 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0002_auto_20210302_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='preguntas',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='respuestas',
            field=models.CharField(default='', max_length=50),
        ),
    ]
