# Generated by Django 3.1.4 on 2021-03-03 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0003_auto_20210302_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='apellidos',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='dni',
            field=models.CharField(default='', max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='fechaNacimiento',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nombres',
            field=models.CharField(default='', max_length=35),
        ),
    ]
