# Generated by Django 3.1.4 on 2021-03-03 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0004_auto_20210302_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(default='', max_length=35)),
                ('apellidos', models.CharField(default='', max_length=35)),
                ('usuario', models.CharField(default='', max_length=50)),
                ('pasword', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('numeroDeCelular', models.CharField(default='', max_length=50)),
                ('fechaNacimiento', models.DateField(default='')),
                ('tarjetaCedula', models.CharField(choices=[('T', 'Tarjeta de identidad'), ('C', 'Cedula')], default='T', max_length=1)),
                ('numeroDeTarjetaCedula', models.CharField(default='', max_length=50)),
                ('preguntaDeSeguridad', models.CharField(choices=[('1', 'Pregunta 1'), ('2', 'Pregunta 2'), ('3', 'Pregunta 3')], default='1', max_length=1)),
                ('respuesta', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
