# Generated by Django 3.1.4 on 2021-03-25 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0006_camposarts'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvMusica',
            fields=[
                ('materialess', models.CharField(choices=[('P', 'Piano'), ('G', 'Guitarra'), ('B', 'Bafle'), ('M', 'Microfono')], default='', max_length=1, primary_key=True, serialize=False)),
                ('disponible', models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='', max_length=1)),
                ('Fecha', models.DateField(default='')),
            ],
        ),
        migrations.RenameField(
            model_name='studentlogin',
            old_name='numeroDeTarjetaCedula',
            new_name='numeroDeCelularoDeTarjetaCedula',
        ),
    ]
