# Generated by Django 3.1.4 on 2021-03-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0007_auto_20210324_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camposarts',
            name='camposss',
            field=models.CharField(choices=[('Fotografia', 'Fotografia'), ('Danzas', 'Danzas'), ('Futbol', 'Futbol'), ('Basquetboll', 'Basquetboll'), ('Musica', 'Musica'), ('Expresion Corporal', 'Expresion Corporal'), ('Pintura', 'Pintura')], default='', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invmusica',
            name='disponible',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='invmusica',
            name='materialess',
            field=models.CharField(choices=[('Piano', 'Piano'), ('Guitarra', 'Guitarra'), ('Bafle', 'Bafle'), ('Microfono', 'Microfono')], default='', max_length=50, primary_key=True, serialize=False),
        ),
    ]
