# Generated by Django 3.1.4 on 2021-04-10 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0009_invpintura'),
    ]

    operations = [
        migrations.AddField(
            model_name='invmusica',
            name='codigo',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='invpintura',
            name='codigo',
            field=models.CharField(default='', max_length=50),
        ),
    ]
