# Generated by Django 3.1.4 on 2021-04-18 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0010_auto_20210409_2320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invmusica',
            old_name='Fecha',
            new_name='Fecha_Solicitado',
        ),
        migrations.RenameField(
            model_name='invpintura',
            old_name='Fecha',
            new_name='Fecha_Solicitado',
        ),
        migrations.AlterField(
            model_name='invmusica',
            name='disponible',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='invmusica',
            name='materialess',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invpintura',
            name='disponible',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='invpintura',
            name='materialess',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
        ),
    ]
