# Generated by Django 3.1.4 on 2021-04-22 12:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0014_auto_20210422_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invdanzas',
            name='Fecha_Solicitado',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='invdeportes',
            name='Fecha_Solicitado',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='invfoto',
            name='Fecha_Solicitado',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='invpintura',
            name='Fecha_Solicitado',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='invta',
            name='Fecha_Solicitado',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
