# Generated by Django 3.1.4 on 2021-04-24 00:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0015_auto_20210422_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='invdanzas',
            name='Fecha_Limite',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='invdeportes',
            name='Fecha_Limite',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='invfoto',
            name='Fecha_Limite',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='invmusica',
            name='Fecha_Limite',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='invpintura',
            name='Fecha_Limite',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='invta',
            name='Fecha_Limite',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
