# Generated by Django 3.1.4 on 2021-04-24 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0016_auto_20210423_1948'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentLogin',
        ),
    ]
