# Generated by Django 3.1.4 on 2021-04-24 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0017_delete_studentlogin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvMusica',
        ),
    ]
