# Generated by Django 3.1.4 on 2021-04-24 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0019_inv_musica'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvPintura',
        ),
    ]
