# Generated by Django 3.1.4 on 2021-04-24 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0021_inv_pintura'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvTA',
        ),
    ]
