# Generated by Django 3.1.4 on 2021-04-24 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0025_inv_deportes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvDanzas',
        ),
    ]
