# Generated by Django 3.1.4 on 2021-04-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0029_inv_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inv_foto',
            name='codigo',
            field=models.AutoField(default='', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inv_foto',
            name='materialess',
            field=models.CharField(default='', max_length=50),
        ),
    ]
