# Generated by Django 3.1.4 on 2021-04-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0031_auto_20210424_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inv_foto',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
