# Generated by Django 3.1.4 on 2021-04-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0032_auto_20210424_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inv_danzas',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inv_danzas',
            name='materialess',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='inv_deportes',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inv_deportes',
            name='materialess',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='inv_musica',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inv_musica',
            name='materialess',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='inv_pintura',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inv_pintura',
            name='materialess',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='inv_ta',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inv_ta',
            name='materialess',
            field=models.CharField(default='', max_length=50),
        ),
    ]
