# Generated by Django 3.1.4 on 2021-04-24 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0039_auto_20210424_1222'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CamposArts',
        ),
        migrations.RemoveField(
            model_name='permisodoc',
            name='Pest',
        ),
        migrations.RemoveField(
            model_name='permisoest',
            name='Pest',
        ),
        migrations.DeleteModel(
            name='Docentes',
        ),
        migrations.DeleteModel(
            name='PermisoDoc',
        ),
        migrations.DeleteModel(
            name='PermisoEst',
        ),
    ]
