# Generated by Django 3.1.4 on 2021-04-24 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Academico', '0040_auto_20210424_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inv_danzas',
            name='Fecha_Limite',
        ),
        migrations.RemoveField(
            model_name='inv_danzas',
            name='Fecha_Solicitado',
        ),
        migrations.RemoveField(
            model_name='inv_danzas',
            name='user',
        ),
        migrations.RemoveField(
            model_name='inv_foto',
            name='Fecha_Limite',
        ),
        migrations.RemoveField(
            model_name='inv_foto',
            name='Fecha_Solicitado',
        ),
        migrations.RemoveField(
            model_name='inv_foto',
            name='user',
        ),
        migrations.AddField(
            model_name='inv_danzas',
            name='Estado',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='inv_deportes',
            name='Estado',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='inv_musica',
            name='Estado',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='inv_pintura',
            name='Estado',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='inv_ta',
            name='Estado',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='pedir_deportes',
            name='Fecha_Solicitado',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pedir_pintura',
            name='Fecha_Solicitado',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pedir_ta',
            name='Fecha_Solicitado',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='Pedir_Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedir', models.PositiveSmallIntegerField()),
                ('Fecha_Solicitado', models.DateField()),
                ('Fecha_Limite', models.DateField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.inv_foto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_foto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pedir_Danzas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedir', models.PositiveSmallIntegerField()),
                ('Fecha_Solicitado', models.DateField()),
                ('Fecha_Limite', models.DateField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.inv_danzas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_danza', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
