# Generated by Django 3.1.4 on 2021-04-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0041_auto_20210424_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='inv_foto',
            name='Estado',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='pedir_musica',
            name='Fecha_Solicitado',
            field=models.DateField(),
        ),
    ]
