# Generated by Django 3.1.4 on 2021-04-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0043_auto_20210424_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inv_danzas',
            name='disponible',
            field=models.PositiveSmallIntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='inv_deportes',
            name='disponible',
            field=models.PositiveSmallIntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='inv_foto',
            name='disponible',
            field=models.PositiveSmallIntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='inv_pintura',
            name='disponible',
            field=models.PositiveSmallIntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='inv_ta',
            name='disponible',
            field=models.PositiveSmallIntegerField(default=''),
        ),
    ]
