# Generated by Django 3.1.4 on 2021-04-24 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Academico', '0044_auto_20210424_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedir_danzas',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HDanzas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedir_deportes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HDepo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedir_foto',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HFoto', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedir_pintura',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HPint', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedir_ta',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HTA', to=settings.AUTH_USER_MODEL),
        ),
    ]
