# Generated by Django 3.1.4 on 2021-04-24 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Academico', '0045_auto_20210424_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedir_musica',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HMusi', to=settings.AUTH_USER_MODEL),
        ),
    ]
