# Generated by Django 3.1.4 on 2021-05-05 14:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0047_auto_20210505_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedir_musica',
            name='Fecha_Limite',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
