# Generated by Django 3.1.4 on 2021-05-05 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0052_auto_20210505_0937'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pedir_Musica',
        ),
    ]
