# Generated by Django 3.1.4 on 2021-05-05 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Academico', '0055_auto_20210505_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedir_TA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedir', models.PositiveSmallIntegerField()),
                ('Fecha_Solicitado', models.DateTimeField(default=django.utils.timezone.now)),
                ('Fecha_a_Pedir', models.DateField(default=django.utils.timezone.now)),
                ('Fecha_Limite', models.DateField(default=django.utils.timezone.now)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.inv_ta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HTA', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pedir_Pintura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedir', models.PositiveSmallIntegerField()),
                ('Fecha_Solicitado', models.DateTimeField(default=django.utils.timezone.now)),
                ('Fecha_a_Pedir', models.DateField(default=django.utils.timezone.now)),
                ('Fecha_Limite', models.DateField(default=django.utils.timezone.now)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.inv_pintura')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HPint', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pedir_Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedir', models.PositiveSmallIntegerField()),
                ('Fecha_Solicitado', models.DateTimeField(default=django.utils.timezone.now)),
                ('Fecha_a_Pedir', models.DateField(default=django.utils.timezone.now)),
                ('Fecha_Limite', models.DateField(default=django.utils.timezone.now)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.inv_foto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HFoto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pedir_Deportes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedir', models.PositiveSmallIntegerField()),
                ('Fecha_Solicitado', models.DateTimeField(default=django.utils.timezone.now)),
                ('Fecha_a_Pedir', models.DateField(default=django.utils.timezone.now)),
                ('Fecha_Limite', models.DateField(default=django.utils.timezone.now)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.inv_deportes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HDepo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pedir_Danzas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedir', models.PositiveSmallIntegerField()),
                ('Fecha_Solicitado', models.DateTimeField(default=django.utils.timezone.now)),
                ('Fecha_a_Pedir', models.DateField(default=django.utils.timezone.now)),
                ('Fecha_Limite', models.DateField(default=django.utils.timezone.now)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.inv_danzas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HDanzas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
