# Generated by Django 3.1.4 on 2021-05-06 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0056_pedir_danzas_pedir_deportes_pedir_foto_pedir_pintura_pedir_ta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='carrera',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='estudiante',
        ),
        migrations.DeleteModel(
            name='Carrera',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
        migrations.DeleteModel(
            name='Matricula',
        ),
    ]
