# Generated by Django 3.1.4 on 2021-05-06 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0057_auto_20210505_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedir_deportes',
            name='material',
        ),
        migrations.RemoveField(
            model_name='pedir_deportes',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pedir_foto',
            name='material',
        ),
        migrations.RemoveField(
            model_name='pedir_foto',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pedir_musica',
            name='material',
        ),
        migrations.RemoveField(
            model_name='pedir_musica',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pedir_pintura',
            name='material',
        ),
        migrations.RemoveField(
            model_name='pedir_pintura',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pedir_ta',
            name='material',
        ),
        migrations.RemoveField(
            model_name='pedir_ta',
            name='user',
        ),
        migrations.DeleteModel(
            name='Pedir_Danzas',
        ),
        migrations.DeleteModel(
            name='Pedir_Deportes',
        ),
        migrations.DeleteModel(
            name='Pedir_Foto',
        ),
        migrations.DeleteModel(
            name='Pedir_Musica',
        ),
        migrations.DeleteModel(
            name='Pedir_Pintura',
        ),
        migrations.DeleteModel(
            name='Pedir_TA',
        ),
    ]
