# Generated by Django 3.1.4 on 2021-05-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0059_pedir_danzas_pedir_deportes_pedir_foto_pedir_musica_pedir_pintura_pedir_ta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedir_musica',
            name='pedir',
            field=models.IntegerField(),
        ),
    ]
