# Generated by Django 3.1.4 on 2021-05-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0062_auto_20210522_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inv_danzas',
            name='disponible',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inv_deportes',
            name='disponible',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inv_foto',
            name='disponible',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inv_musica',
            name='disponible',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inv_pintura',
            name='disponible',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inv_ta',
            name='disponible',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pedir_danzas',
            name='pedir',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pedir_deportes',
            name='pedir',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pedir_foto',
            name='pedir',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pedir_pintura',
            name='pedir',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pedir_ta',
            name='pedir',
            field=models.IntegerField(),
        ),
    ]
