# Generated by Django 3.1.4 on 2021-04-21 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0003_postdanzas_postdeportes_postmusica_postpintura_postta'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='batman.png', upload_to=''),
        ),
    ]
