# Generated by Django 3.1.4 on 2021-04-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0006_auto_20210423_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='user_3.png', upload_to=''),
        ),
    ]
