# Generated by Django 3.1.4 on 2021-04-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0007_auto_20210425_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='user_3.png', upload_to=''),
        ),
    ]
