# Generated by Django 3.1.4 on 2021-04-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0009_auto_20210427_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='user_3.png', upload_to=''),
        ),
    ]
