# Generated by Django 3.1.4 on 2021-05-06 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0011_auto_20210427_1715'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
