# Generated by Django 3.1.4 on 2021-05-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0014_auto_20210505_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Apellidos',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='Celular',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='Correo',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='profile',
            name='Nombres',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='Telefono',
            field=models.CharField(default='', max_length=100),
        ),
    ]
