# Generated by Django 3.1.4 on 2021-05-12 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0016_profile_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
