# Generated by Django 3.1.4 on 2021-05-12 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0017_delete_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postdeportes',
            name='user',
        ),
        migrations.RemoveField(
            model_name='postfotografia',
            name='user',
        ),
        migrations.RemoveField(
            model_name='postmusica',
            name='user',
        ),
        migrations.RemoveField(
            model_name='postpintura',
            name='user',
        ),
        migrations.RemoveField(
            model_name='postta',
            name='user',
        ),
        migrations.DeleteModel(
            name='PostDanzas',
        ),
        migrations.DeleteModel(
            name='PostDeportes',
        ),
        migrations.DeleteModel(
            name='PostFotografia',
        ),
        migrations.DeleteModel(
            name='PostMusica',
        ),
        migrations.DeleteModel(
            name='PostPintura',
        ),
        migrations.DeleteModel(
            name='PostTA',
        ),
    ]
