# Generated by Django 3.1.4 on 2021-05-24 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0019_post_postdanzas_postdeportes_postfotografia_postmusica_postpintura_postta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Apellidos',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Correo',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Nombres',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Usuario',
        ),
    ]
