# Generated by Django 3.1.4 on 2021-05-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0020_auto_20210523_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AddField(
            model_name='profile',
            name='codigo',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
