# Generated by Django 3.1.4 on 2021-06-01 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0022_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateField(verbose_name='Fecha y Hora final   '),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateField(verbose_name='Fecha y Hora inicio'),
        ),
    ]
