# Generated by Django 3.1.4 on 2021-06-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0026_auto_20210531_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Numero_de_Documento_de_Identidad',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='Tipo_de_Documento_de_Identidad',
            field=models.CharField(choices=[('Cedula', 'Cedula'), ('Tarjeta de Identidad', 'Tarjeta de Identidad')], default='Tarjeta de Identidad', max_length=20),
        ),
    ]
