# Generated by Django 3.1.4 on 2021-06-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0027_auto_20210601_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Celular',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Telefono',
            field=models.CharField(default='', max_length=7),
        ),
    ]
