# Generated by Django 3.1.4 on 2021-06-02 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0029_eventmember'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventMember',
        ),
    ]
