# Generated by Django 3.1.4 on 2021-06-13 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0031_logos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='user_3.png', null=True, upload_to=''),
        ),
    ]
