# Generated by Django 3.1.4 on 2021-06-13 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0032_auto_20210612_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
