# Generated by Django 3.1.4 on 2021-06-13 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0033_auto_20210612_2006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
