# Generated by Django 3.1.4 on 2021-06-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0035_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='archivos/'),
        ),
    ]
