# Generated by Django 3.1.4 on 2021-06-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0038_auto_20210615_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='perfiles/user_3.png', null=True, upload_to='perfiles/'),
        ),
    ]
