# Generated by Django 3.1.4 on 2021-06-19 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0039_auto_20210615_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titulo'),
        ),
    ]
